version: '2.1'

jobs:
  install_node:
    docker:
     - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: install node modules
          command: npm install --save
  build_docker:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker Image
          command: docker build -t lokeshb003/circleci-nodejs-app:latest . && docker login -u lokeshb003 -p kepler22b && docker push lokeshb003/circleci-nodejs-app:latest

workflows:
  build_test:
    jobs:
      - install_node
      - build_docker   